new touchsliderwizard, can be used as mutual and selfcap slider
KiCad/kicad-footprint-wizards pull request #5
Opened 2019-10-28 16:03 UTC by Canwail-Modular

added Mutual capacitance Capacitive Touch Button.
Measurements are taken from [QTAN0079](http://ww1.microchip.com/downloads/en/appnotes/doc10752.pdf), Page 37.

------------

Thanks for creating a pull request to contribute to the KiCad footprint wizards! To speed up integration of your PR, please check the following items:

- [x] Provide a description for your PR (are you creating a new wizard or improving an existing one?)
- [x] Include a screenshot of the wizard screen with an example created footprint

![Screenshot_748](https://user-images.githubusercontent.com/50383630/66079295-0f700280-e564-11e9-86a4-af6b69885a7a.png)

2020-07-03 21:52 UTC, sethhillbrand requested changes

2020-07-03 21:52 UTC, sethhillbrand commented on touch_slider_wizard.py
> +        #layerset.AddLayer(pcbnew.F_Mask)
Try not leave commented lines unless required to explain the action

2020-07-03 21:52 UTC, sethhillbrand commented on touch_slider_wizard.py
> +        #layerset.AddLayer(pcbnew.F_Mask)
Try not to leave commented lines unless required to explain the action of existing code.

2020-07-03 21:52 UTC, sethhillbrand commented on touch_slider_wizard.py
> +        yElectrodeCount     = (int)(((pcbnew.ToMM(touch_width)-4)/yElectrodeSpacing))+1
Please use consistent spacing (spaces around operators such as '-' and '/' and '+'

Also, use Pythonic integer casting, i.e. int(x / y) rather than C-style (int)(x / y)

2020-07-03 21:52 UTC, sethhillbrand commented on touch_slider_wizard.py
> +        yPosition     = (pcbnew.ToMM(touch_width)/2)-((pcbnew.ToMM(touch_width)-((yElectrodeCount-1)*yElectrodeSpacing))/2.0)
Please use spacing around operators and wrap this line at column 99 or less for readability

2020-08-12 13:44 UTC, sethhillbrand commented
@Canwail-Modular ping

2020-08-22 20:00 UTC, canwail commented
Sorry, totally forgot about that thing.
The name of the thin transmission electrode in the settings menu is currently "y-width" (as in Y-Electrode as Atmel calls it), what name would you give it? The only visually-descriptive name I can think of would be top and bottom electrode, but that doesnt make sense because it might be upside down.

Also this wizard doesnt follow the App note 100% because the size parameter of the original slider wizard isnt quite correct (For example if you set the slider length to 120mm its not 120mm edge to edge but more like 124) but unless you are making huge sliders, that shouldnt be any problem, the sensitivity on the ends of the sliders is already bad anyway (says Atmel).

Finally, the wizard looks wrong in the generator preview right now (the unaltered original also), its fine if you export it and then view it in the 3d renderer. Will check if thats the case on linux too, just so i can rule out a possible faulty Windows installation.
Edit: Looks fine on Linux, ignore the upper paragraph. My kicad installation is probably just broken.

2020-08-28 20:38 UTC, merged

2020-08-28 20:39 UTC, sethhillbrand commented
Looks good.  Thank you for your contribution

2020-08-28 20:41 UTC, canwail commented
Are you sure you dont want the "y-width" changed to something else?