add mutual capacitance button
KiCad/kicad-footprint-wizards pull request #6
Opened 2019-10-28 16:08 UTC by Canwail-Modular

added Mutual capacitance Capacitive Touch Button.
Measurements are taken from [QTAN0079](http://ww1.microchip.com/downloads/en/appnotes/doc10752.pdf), Page 37.

------------

Thanks for creating a pull request to contribute to the KiCad footprint wizards! To speed up integration of your PR, please check the following items:

- [x] Provide a description for your PR (are you creating a new wizard or improving an existing one?)
- [x] Include a screenshot of the wizard screen with an example created footprint

![Screenshot_748](https://user-images.githubusercontent.com/50383630/66079295-0f700280-e564-11e9-86a4-af6b69885a7a.png)

2019-10-28 17:28 UTC, poeschlr commented
I am not sure if this repo is the right place to contribute footprint wizards. We might need to ask over on the mailing list about that.

2020-07-03 21:57 UTC, sethhillbrand commented
I think we'll clear out the old PRs here before moving over to GitLab.

2020-07-03 21:59 UTC, sethhillbrand requested changes

2020-07-03 21:59 UTC, sethhillbrand commented on mutualcap_button_wizard.py
> +        self.AddParam("Pads", "T (Panel thickness)", self.uMM, 1.6)
The values 'T' and 'Y width' are hard to parse.  I see they are used that way by Atmel, but let's get a better description.  Maybe "Surrounding Width"?

2020-07-05 12:08 UTC, Canwail-Modular commented on mutualcap_button_wizard.py
> +        self.AddParam("Pads", "T (Panel thickness)", self.uMM, 1.6)
How about pt (panel thickness) and re and de for Drive/Receive electrode? Drive Electrode (currently X) is the thick surrounding one while Receive Electrode (currently Y) would be the inner thin one. 
Just calling it "Surrounding Width" i think would be a bit unclear as to what it is because the Drive Electrode "Finger" thickness also depends on that parameter.

2020-07-05 14:53 UTC, sethhillbrand commented on mutualcap_button_wizard.py
> +        self.AddParam("Pads", "T (Panel thickness)", self.uMM, 1.6)
I'd prefer to stay away from functional representations.  Instead, let's keep the graphical representations.  Maybe "Inner width" and "Outer width"?  Thickness tends to refer to the z-direction so is confusing in this context.

2020-07-05 21:02 UTC, sethhillbrand commented on mutualcap_button_wizard.py
> +        self.AddParam("Pads", "T (Panel thickness)", self.uMM, 1.6)
I see that inner is changed but there is still "Panel Thickness".  This is an uncommon term.  It would be good to rename it.  If you dislike "Outer width", you might call it "Frame Width".

2020-07-06 00:28 UTC, Canwail-Modular commented on mutualcap_button_wizard.py
> +        self.AddParam("Pads", "T (Panel thickness)", self.uMM, 1.6)
I think there is a misunderstanding. The "Panel Thickness" refers to the thickness (z-direction) of whatever graphics panel or protection layer you put physically above the touchpad on the PCB (For example a acrylic sheet as graphical overlay or protection so that you dont touch the pcb directly). The "Outer width" is derived from the other parameters and can not be manually entered as a number.

Atmel calls it a front panel, Cypress (where this picture is from) calls it Overlay
![article-2016december-simplifying-capacitive-touch-fig1](https://www.digikey.be/-/media/Images/Article%20Library/TechZone%20Articles/2016/December/Simplifying%20Capacitive%20Touch%20Sensor%20Design%20Cypress%20CY8CKIT/article-2016december-simplifying-capacitive-touch-fig1.jpg)

The internal variables were already changed to have i and o prefixes for inner and outer.

2020-07-06 02:42 UTC, sethhillbrand commented on mutualcap_button_wizard.py
> +        self.AddParam("Pads", "T (Panel thickness)", self.uMM, 1.6)
Thank you for that additional information.  I wasn't away of the relationship.

That being said, the border width or frame width is the same value as the overlay thickness in this recommended implementation.  A user would not be expected to know the relationship but they would be concerned about the width of the copper that is generated.  You could explain the relationship in the wizard description text but I'd prefer that the parameter be focused on the copper that is generated.

2020-07-07 07:40 UTC, Canwail-Modular commented on mutualcap_button_wizard.py
> +        self.AddParam("Pads", "T (Panel thickness)", self.uMM, 1.6)
okay, parameter strings have been changed to inner and outer

2020-08-12 13:37 UTC, merged